services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: phys_db
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U john9francis"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_app:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.prod
